version: '3'
services:
    web:
        image: nginx
        ports:
            - "8000:80"
        depends_on:
            - app
        volumes:
            - ./docker/nginx_conf/default.conf:/etc/nginx/conf.d/default.conf
            - ./document_root:/var/www/html
            
    app:
        build: ./docker/php
        ports:
            - "9000:8080"
            - "1080:1080"
        depends_on:
            - mysql
        volumes:
            - ./document_root:/var/www/html

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: laravel_db
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: team_a_gtb2021
            MYSQL_ROOT_PASSWORD: team_a_gtb2021_root
        command: --disable-partition-engine-check        
        ports:
            - "3300:3306"
        volumes:
            - mysql-data:/var/lib/mysql
            

volumes:
    mysql-data:
